#!/usr/bin/env node

/* globals require process */

require('./util/work-from-root')();

var cleanDirectory = require('./util/clean-directory');
var buildProject = require('./util/build-project');
var docBuilder = require('./util/build-doc');

var buildPath = 'dist';

cleanDirectory(buildPath);

process.env.BROCCOLI_ENV = 'production';

console.log('Building ....');
buildProject(buildPath, function (buildStatus) {
  console.log('Done building');
  if (buildStatus !== 0) {
    return process.exit(buildStatus);
  }

  console.log('Creating build files')
  docBuilder.createSrc(function (error, paths) {
   if (error) {
     console.log(error);
   } else {
      docBuilder.generateDocs(paths, true, function () { 

      });
   }
  });
});
