#!/usr/bin/env node

/* globals require process */

require('./util/work-from-root')();

var cleanDirectory = require('./util/clean-directory');
var buildProject = require('./util/build-project');
var buildDoc = require('./util/build-doc');

var buildPath = 'dist';

cleanDirectory(buildPath);

process.env.BROCCOLI_ENV = 'production';

buildProject(buildPath, function (buildStatus) {
  process.exit(buildStatus);
});

buildDoc(function (error) {
	if (error) {
		console.error(error);
	}
});